// eslint-disable-next-line import/no-anonymous-default-export
export default [
    {
        hora: '9:00 - 10:00',
        lunes: 'Funcional',
        profelunes: 'Prof. Luisina Micheloud',
        martes: 'Gimnasia adultos mayores',
        profemartes: 'Prof. Luisina Micheloud',
        miercoles: 'Funcional',
        profemiercoles: 'Prof. Luisina Micheloud',
        jueves: 'Gimnasia adultos mayores',
        profejueves: 'Prof. Luisina Micheloud',
        viernes: '',
        profeviernes: '',
    },
    {
        hora: '13:30 - 14-30',
        lunes: '',
        profelunes: '',
        martes: '',
        profemartes: '',
        miercoles: '',
        profemiercoles:  '',
        jueves: '',
        profejueves: '',
        viernes: 'Funcional',
        profeviernes: 'Prof. Luisina Micheloud',
    },
    {
        hora: '14:00 - 15:00',
        lunes: 'Localizada',
        profelunes: 'Prof. Luisina Micheloud',
        martes: 'Funcional',
        profemartes: 'Prof. Luisina Micheloud',
        miercoles: 'Localizada',
        profemiercoles:  'Prof. Luisina Micheloud',
        jueves: 'Funcional',
        profejueves: 'Prof. Luisina Micheloud',
        viernes: '',
        profeviernes: '',
    },
    {
        hora: '14:30 - 15:30',
        lunes: '',
        profelunes: '',
        martes: '',
        profemartes: '',
        miercoles: '',
        profemiercoles:  '',
        jueves: '',
        profejueves: '',
        viernes: 'Localizada',
        profeviernes: 'Prof. Luisina Micheloud',
    },
    {
        hora: '15:00 - 16:00',
        lunes: '',
        profelunes: '',
        martes: 'Localizada',
        profemartes: 'Prof. Luisina Micheloud',
        miercoles: '',
        profemiercoles:  '',
        jueves: 'Localizada',
        profejueves: 'Prof. Luisina Micheloud',
        viernes: '',
        profeviernes: '',
    },
    {
        hora: '18:00 - 19:00',
        lunes: 'Localizada',
        profelunes: 'Prof. Luisina Micheloud',
        martes: '',
        profemartes: '',
        miercoles: 'Localizada',
        profemiercoles:  'Prof. Luisina Micheloud',
        jueves: '',
        profejueves: '',
        viernes: '',
        profeviernes: '',
    },
    {
        hora: '19:00 - 20:00',
        lunes: 'Funcional',
        profelunes: 'Prof. Luisina Micheloud',
        martes: 'Localizada',
        profemartes: 'Prof. Rita Milajer',
        miercoles: 'Funcional',
        profemiercoles:  'Prof. Luisina Micheloud',
        jueves: 'Localizada',
        profejueves: 'Prof. Rita Milajer',
        viernes: '',
        profeviernes: '',
    },
    {
        hora: '20:00 - 21:00',
        lunes: 'Funcional',
        profelunes: 'Prof. Luisina Micheloud',
        martes: 'Localizada',
        profemartes: 'Prof. Rita Milajer',
        miercoles: 'Funcional',
        profemiercoles:  'Prof. Luisina Micheloud',
        jueves: 'Localizada',
        profejueves: 'Prof. Rita Milajer',
        viernes: '',
        profeviernes: '',
    }
    
];